const bridge = window.codex || null;
const meta={chat:['智能对话','与模型一起完成任何工作'],tasks:['定时任务','自动执行重复工作'],usage:['用量统计','Token 与费用一目了然'],models:['模型中心','连接你的 AI 服务商'],plugins:['Skills & MCP','扩展 Codex Flow 的能力'],video:['视频工作室','AI 驱动的自动剪辑'],cli:['CLI 控制台','图形界面与终端无缝协作']};
let publicConfig={configured:false,provider:null};
let activeRequestId=null;
let removeChatListener=null;
const byId=id=>document.getElementById(id);

function page(name){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.side nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));byId('title').textContent=meta[name][0];byId('subtitle').textContent=meta[name][1]}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>page(x.dataset.page));

const taskData=[['☀','s-green','每日 AI 资讯早报','搜索当天 AI 行业重要资讯，整理成中文摘要并发送通知。','每天 08:00:00','18 小时后',true],['↗','s-violet','竞品动态监控','监控 8 个竞品网站与社交账号，发现更新时生成报告。','每 4 小时','42 分钟后',true],['▰','s-orange','视频素材自动整理','扫描下载目录，识别视频内容并按主题自动分类。','每天 23:30:00','14 小时后',true],['▣','','周报自动生成','汇总本周项目提交与任务进度，生成结构化工作周报。','每周五 18:00','—',false]];
byId('taskList').innerHTML=taskData.map(t=>'<article class="task-row"><i class="'+t[1]+'">'+t[0]+'</i><span><b>'+t[2]+'</b><p>'+t[3]+'</p><small>◷ '+t[4]+'</small><small>◇ GPT-5.4</small></span><em>下次执行<br><b>'+t[5]+'</b></em><button class="toggle '+(t[6]?'on':'')+'"><i></i></button></article>').join('');

const codingPlanPresets={'火山方舟 Coding Plan':{baseUrl:'https://ark.cn-beijing.volces.com/api/coding/v3',model:'ark-code-latest'},'阿里云百炼 Coding Plan':{baseUrl:'https://coding.dashscope.aliyuncs.com/v1',model:'qwen3.7-plus'},'智谱 GLM Coding Plan':{baseUrl:'https://open.bigmodel.cn/api/coding/paas/v4',model:'glm-5.2'},'腾讯云 Coding Plan':{baseUrl:'https://api.lkeap.cloud.tencent.com/coding/v3',model:'tc-code-latest'}};
const providerCatalog=[['◉','OpenAI','https://api.openai.com/v1','GPT-5.4,GPT-5 mini,o3',true],['火','火山方舟 Coding Plan','https://ark.cn-beijing.volces.com/api/coding/v3','ark-code-latest,Doubao-Seed-2.0-Code,GLM-5.2,Kimi-K2.7,MiniMax-M3,DeepSeek-V4',true],['阿','阿里云百炼 Coding Plan','https://coding.dashscope.aliyuncs.com/v1','qwen3.7-plus,qwen3.6-plus,Kimi-K2.5,GLM-5,MiniMax-M2.5,Qwen3-Coder',true],['GLM','智谱 GLM Coding Plan','https://open.bigmodel.cn/api/coding/paas/v4','glm-5.2,glm-5-turbo,glm-5.1,glm-5,glm-4.7,glm-4.5-air',true],['腾','腾讯云 Coding Plan','https://api.lkeap.cloud.tencent.com/coding/v3','tc-code-latest,GLM-5,Kimi K2.5,MiniMax M2.5',true],['AI','Anthropic','https://api.anthropic.com','原生协议适配中',false],['G','Google AI','https://generativelanguage.googleapis.com','原生协议适配中',false],['D','DeepSeek','https://api.deepseek.com/v1','DeepSeek Chat,DeepSeek Reasoner',true],['Q','通义千问','https://dashscope.aliyuncs.com/compatible-mode/v1','Qwen Max,Qwen Coder',true],['＋','自定义服务商','','OpenAI 兼容接口',true]];
function renderProviders(){const current=publicConfig.provider;byId('providers').innerHTML=providerCatalog.map(p=>{const connected=current&&(current.name===p[1]||current.baseUrl===p[2]);const modelIds=connected&&current.models?.length?current.models.map(x=>x.id):p[3].split(',').filter(Boolean);const visible=modelIds.slice(0,5);if(modelIds.length>5)visible.push('+'+(modelIds.length-5)+' 个模型');return '<article class="provider '+(connected?'connected':'')+'"><div class="provider-head"><i>'+p[0]+'</i><span><b>'+p[1]+'</b><small>'+p[2]+'</small></span><em>'+(connected?'已连接':'未连接')+'</em></div><div class="provider-models">'+visible.map(m=>'<span>'+m+'</span>').join('')+'</div><div class="provider-foot"><span>'+(p[1].includes('Coding Plan')?'共 '+modelIds.length+' 个模型 · 套餐专用 Key':connected?'本机安全存储':'填写 Key 后自动获取模型')+'</span><button class="'+(p[4]?'open-provider':'provider-pending')+'" data-name="'+p[1]+'" data-url="'+p[2]+'">'+(connected?'管理':p[4]?'连接':'即将支持')+'</button></div></article>'}).join('')}
renderProviders();

const pluginData=[['◎','Browser MCP','让 AI 操作浏览器，完成搜索、填表、采集与网页测试。','128K',true],['▣','GitHub MCP','管理仓库、Issue、PR 与 Actions，让开发流程自动化。','96K',false],['✦','Image Studio','优先调用图片模型，失败时自动生成 H5 并转为图片。','82K',true],['⌕','Deep Research','多源深度检索、交叉验证，输出专业研究报告。','74K',false],['N','Notion MCP','读取和更新知识库，自动整理会议、文档和项目。','68K',false],['▤','Office Master','创建和编辑 Word、Excel、PPT 与 PDF 文档。','53K',false]];
byId('pluginGrid').innerHTML=pluginData.map(p=>'<article class="plugin"><div class="plugin-head"><i>'+p[0]+'</i><button class="'+(p[4]?'installed':'install')+'">'+(p[4]?'✓ 已安装':'安装')+'</button></div><h3>'+p[1]+'</h3><p>'+p[2]+'</p><small>★★★★★ 4.9　 '+p[3]+' 安装</small></article>').join('');

document.querySelectorAll('.toggle').forEach(x=>x.onclick=()=>x.classList.toggle('on'));
const promptBox=byId('prompt'),sendButton=byId('send'),composer=document.querySelector('.composer');
document.querySelectorAll('[data-prompt]').forEach(x=>x.onclick=()=>{promptBox.value=x.dataset.prompt;promptBox.focus()});

function prepareConversation(value,isReal){byId('hero').classList.add('hide');byId('conversation').classList.remove('hide');byId('userText').textContent=value;byId('thinking').classList.remove('hide');byId('thinking').textContent=isReal?'● ● ● 正在连接模型并等待响应...':'● ● ● 正在调用 Web Search 和 AI News Skill...';const answer=byId('answer');answer.classList.add('hide');answer.innerHTML='<p id="answerText"></p><div class="answer-actions"><button>复制</button><button>导出报告</button><button id="answerSchedule">创建每日任务</button></div>';}

function demoResponse(){setTimeout(()=>{byId('thinking').classList.add('hide');byId('answer').classList.remove('hide');byId('answerText').textContent='演示模式已完成任务。连接 API Key 后，这里将显示模型的真实流式回复。';byId('inToken').textContent='1.2K';byId('outToken').textContent='286';byId('cost').textContent='演示'},900)}

function handleChatEvent(event){if(event.requestId!==activeRequestId)return;if(event.type==='delta'){byId('thinking').classList.add('hide');byId('answer').classList.remove('hide');byId('answerText').textContent+=event.text}else if(event.type==='usage'){byId('inToken').textContent=formatTokens(event.record.inputTokens);byId('outToken').textContent=formatTokens(event.record.outputTokens);byId('cost').textContent=event.record.estimated?'估算':'已记录'}else if(event.type==='error'){byId('thinking').classList.add('hide');byId('answer').classList.remove('hide');byId('answerText').className='stream-error';byId('answerText').textContent=event.message}else if(event.type==='done'){composer.classList.remove('busy');activeRequestId=null;loadUsage(currentRange())}}

async function sendPrompt(){const value=promptBox.value.trim();if(!value)return;if(activeRequestId&&bridge){await bridge.chat.cancel(activeRequestId);return}promptBox.value='';const useReal=Boolean(bridge&&publicConfig.configured);prepareConversation(value,useReal);if(!useReal){demoResponse();return}activeRequestId=crypto.randomUUID();composer.classList.add('busy');try{await bridge.chat.start({requestId:activeRequestId,model:byId('modelPicker').value,messages:[{role:'user',content:value}]})}catch(error){if(activeRequestId){handleChatEvent({requestId:activeRequestId,type:'error',message:cleanError(error)});composer.classList.remove('busy');activeRequestId=null}}}
sendButton.onclick=sendPrompt;promptBox.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendPrompt()}};

const values={day:['38.6K','42','¥2.86'],month:['2.48M','1,284','¥128.40'],year:['18.9M','9,642','¥986.20'],all:['24.7M','12,804','¥1,328.60']};
function currentRange(){return document.querySelector('[data-range].active')?.dataset.range||'month'}
function formatTokens(value){const n=Number(value||0);if(n>=1000000)return (n/1000000).toFixed(2)+'M';if(n>=1000)return (n/1000).toFixed(1)+'K';return String(n)}
async function loadUsage(range){if(!bridge){const v=values[range];byId('totalToken').textContent=v[0];byId('requests').textContent=v[1];byId('totalCost').textContent=v[2];return}const [summary,records]=await Promise.all([bridge.usage.summary(range),bridge.usage.list(20)]);byId('totalToken').textContent=formatTokens(summary.totalTokens);byId('requests').textContent=summary.requests.toLocaleString('zh-CN');byId('totalCost').textContent='¥'+summary.estimatedCost.toFixed(2);renderUsageRows(records)}
function renderUsageRows(records){const table=document.querySelector('.table-card table');if(!table)return;table.innerHTML='<tr><th>时间</th><th>任务</th><th>模型</th><th>输入</th><th>输出</th><th>总计</th><th>状态</th></tr>'+records.map(r=>'<tr><td>'+new Date(r.createdAt).toLocaleString('zh-CN')+'</td><td>智能对话</td><td>'+r.modelId+'</td><td>'+r.inputTokens+'</td><td>'+r.outputTokens+'</td><td>'+r.totalTokens+'</td><td><b>成功</b></td></tr>').join('')}
document.querySelectorAll('[data-range]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-range]').forEach(y=>y.classList.remove('active'));x.classList.add('active');loadUsage(x.dataset.range)});
const heights=[[38,22],[58,35],[46,28],[72,44],[54,34],[80,48],[69,42],[88,57],[76,48],[95,61]];byId('bars').innerHTML=heights.map(h=>'<span><i style="height:'+h[0]+'%"></i><i style="height:'+h[1]+'%"></i></span>').join('');

function modal(id,on=true){byId(id).classList.toggle('show',on)}function toastMsg(text){byId('toastText').textContent=text;byId('toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>byId('toast').classList.remove('show'),2800)}function cleanError(error){return String(error?.message||error).replace(/^Error invoking remote method '[^']+': Error: /,'')}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal(x.dataset.close,false));document.querySelectorAll('.close-task').forEach(x=>x.onclick=()=>modal('taskModal',false));
byId('demo').onclick=()=>{modal('welcome',false);toastMsg('已进入演示模式，连接 API Key 后可使用真实模型')};byId('showKey').onclick=()=>byId('apiKey').type=byId('apiKey').type==='password'?'text':'password';

async function connectOnboarding(){const button=byId('connect');const selected=document.querySelector('.choices button.active');const type=selected?.dataset.provider||'openai';const presets={openai:{name:'OpenAI',baseUrl:'https://api.openai.com/v1'},deepseek:{name:'DeepSeek',baseUrl:'https://api.deepseek.com/v1'}};const custom=type==='custom';const name=custom?byId('customProviderName').value.trim():presets[type].name;const baseUrl=custom?byId('customBaseUrl').value.trim():presets[type].baseUrl;const model=custom?byId('customModelId').value.trim():'';if(custom&&(!name||!baseUrl)){toastMsg('请填写服务商名称和 API Base URL');return}if(!bridge){button.querySelector('span').textContent='连接成功';setTimeout(()=>modal('welcome',false),500);return}button.disabled=true;button.querySelector('span').textContent='正在验证并发现模型...';try{publicConfig=await bridge.provider.saveAndDiscover({id:name.toLowerCase().replaceAll(' ', '-'),name,baseUrl,apiKey:byId('apiKey').value,model});applyConfig();modal('welcome',false);toastMsg('连接成功，已载入 '+publicConfig.provider.models.length+' 个模型')}catch(error){toastMsg(cleanError(error));button.querySelector('span').textContent='连接并开始使用'}finally{button.disabled=false}}
byId('connect').onclick=connectOnboarding;

byId('newTask').onclick=()=>modal('taskModal');byId('saveTask').onclick=()=>{modal('taskModal',false);toastMsg('定时任务“'+byId('taskName').value+'”已创建')};
document.addEventListener('click',e=>{const providerButton=e.target.closest('.open-provider');if(providerButton){byId('providerName').value=providerButton.dataset.name==='自定义服务商'?'OpenAI 兼容接口':providerButton.dataset.name;byId('providerBaseUrl').value=providerButton.dataset.url||'';byId('providerModelId').value=codingPlanPresets[providerButton.dataset.name]?.model||'';modal('providerModal')}if(e.target.classList.contains('install')){e.target.textContent='安装中...';setTimeout(()=>{e.target.textContent='✓ 已安装';e.target.className='installed';toastMsg('能力安装完成')},650)}if(e.target.closest('.demo-action')||e.target.closest('.quick'))toastMsg('演示操作已执行')});

byId('providerName').onchange=()=>{const map={'OpenAI':'https://api.openai.com/v1','Google AI':'https://generativelanguage.googleapis.com','DeepSeek':'https://api.deepseek.com/v1','通义千问':'https://dashscope.aliyuncs.com/compatible-mode/v1'};const name=byId('providerName').value;const plan=codingPlanPresets[name];if(plan){byId('providerBaseUrl').value=plan.baseUrl;byId('providerModelId').value=plan.model}else if(map[name]){byId('providerBaseUrl').value=map[name];byId('providerModelId').value=''}};
byId('providerConnect').onclick=async()=>{if(!bridge){modal('providerModal',false);toastMsg('演示连接成功');return}const button=byId('providerConnect');button.disabled=true;button.textContent='正在发现模型...';try{publicConfig=await bridge.provider.saveAndDiscover({id:byId('providerName').value.toLowerCase().replaceAll(' ','-'),name:byId('providerName').value,baseUrl:byId('providerBaseUrl').value,apiKey:byId('providerApiKey').value,model:byId('providerModelId').value});applyConfig();modal('providerModal',false);toastMsg('连接成功，发现 '+publicConfig.provider.models.length+' 个模型')}catch(error){toastMsg(cleanError(error))}finally{button.disabled=false;button.textContent='测试并连接'}};
byId('customPlugin').onclick=()=>toastMsg('已打开自定义 Skill / MCP 配置页');
document.querySelectorAll('.toolbar div button,.category button,.choices button').forEach(x=>x.onclick=()=>{x.parentElement.querySelectorAll('button').forEach(y=>y.classList.remove('active'));x.classList.add('active');if(x.closest('.choices'))byId('onboardingCustom').classList.toggle('hide',x.dataset.provider!=='custom')});

function applyConfig(){renderProviders();const picker=byId('modelPicker');const models=publicConfig.provider?.models||[];picker.innerHTML=models.length?models.map(model=>'<option value="'+model.id+'">'+model.id+'</option>').join(''):'<option>GPT-5.4</option>';if(publicConfig.provider?.model)picker.value=publicConfig.provider.model;document.querySelector('.connection').innerHTML='<span></span> '+(publicConfig.configured?'真实服务已连接':'演示模式');}
byId('modelPicker').onchange=async()=>{if(bridge&&publicConfig.configured){publicConfig=await bridge.provider.setModel(byId('modelPicker').value);toastMsg('默认模型已切换')}};

async function initialize(){if(bridge){removeChatListener=bridge.chat.onEvent(handleChatEvent);try{const [config,plans]=await Promise.all([bridge.config.getPublic(),bridge.codingPlans.list()]);publicConfig=config;for(const plan of plans){codingPlanPresets[plan.name]={baseUrl:plan.baseUrl,model:plan.defaultModel};const entry=providerCatalog.find(item=>item[1]===plan.name);if(entry){entry[2]=plan.baseUrl;entry[3]=plan.models.join(',')}}applyConfig();await loadUsage('month');if(publicConfig.configured)modal('welcome',false)}catch(error){toastMsg(cleanError(error))}}}
window.addEventListener('beforeunload',()=>removeChatListener?.());document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();page('chat');promptBox.focus()}if(e.key==='Escape')document.querySelectorAll('.modal.show').forEach(x=>x.classList.remove('show'))});
initialize();
